FROM --platform=$BUILDPLATFORM swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-console-base:v1.0.0-stable

COPY requirements.txt /tmp/requirements.txt
RUN apk add --no-cache --virtual .build-deps build-base libffi-dev openssl-dev python3-dev git \
    && pip install --upgrade pip \
    && pip install -i https://pypi.tuna.tsinghua.edu.cn/simple --no-cache-dir -r /tmp/requirements.txt \
    && apk del .build-deps build-base libffi-dev openssl-dev python3-dev git
COPY . /app
RUN chmod +x /app/bin/linux/promql-parser