"""update table

Revision ID: 39e88c7b967b
Revises: 
Create Date: 2021-11-25 09:56:42.437607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e88c7b967b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wutong_center_app',
    sa.Column('app_id', sa.String(length=32), nullable=False, comment='应用包'),
    sa.Column('app_name', sa.String(length=64), nullable=True, comment='应用包名'),
    sa.Column('create_user', sa.Integer(), nullable=True, comment='创建人id'),
    sa.Column('create_team', sa.String(length=64), nullable=True, comment='应用所属团队,可以和创建人id不统一'),
    sa.Column('pic', sa.String(length=200), nullable=True, comment='应用头像信息'),
    sa.Column('source', sa.String(length=15), nullable=True, comment='应用来源(本地创建、云商店)'),
    sa.Column('dev_status', sa.String(length=32), nullable=True, comment='开发状态'),
    sa.Column('scope', sa.String(length=50), nullable=True, comment='可用范围'),
    sa.Column('describe', sa.String(length=400), nullable=True, comment='云市应用描述信息'),
    sa.Column('is_ingerit', sa.Boolean(), nullable=True, comment='是否可被继承'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('enterprise_id', sa.String(length=32), nullable=True, comment='企业ID'),
    sa.Column('install_number', sa.Integer(), nullable=True, comment='安装次数'),
    sa.Column('is_official', sa.Boolean(), nullable=True, comment='是否官方认证'),
    sa.Column('details', sa.Text(), nullable=True, comment='应用详情'),
    sa.PrimaryKeyConstraint('app_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wutong_center_app')
    # ### end Alembic commands ###
