name: commit-ci

env:
  BASE_VERSION: v1.0.0

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set ENV
        run: |
          echo "VERSION=${BASE_VERSION}-dev-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1              

      - name: Login to myhuaweicloud-swr
        uses: docker/login-action@v1
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.multiarch
          push: true
          tags: swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-console:${{ env.VERSION }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Deploy console to mng cluster
        id: k8s_deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.MNG_KUBE_CONFIG }}
        with:
          args: set image deployment/wutong-console -n wt-system console=swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-console:${VERSION}